version: 2.1

jobs:
  deploy:
    docker:
      - image: pulumi/pulumi:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install
      - run:
          name: Deploy to GCP
          command: |
            pulumi login --non-interactive $PULUMI_ACCESS_TOKEN
            pulumi stack select $PULUMI_STACK_NAME
            pulumi up --yes --debug

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy
