version: 2.1

jobs:
  deploy:
    docker:
      - image: pulumi/pulumi:latest
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            npm install
      - run:
          name: Deploy to GCP
          command: |
            echo "$GCP_SERVICE_ACCOUNT_KEY" > /tmp/gcp-service-account-key.json
            export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-service-account-key.json
            echo "cat GOOGLE_APPLICATION_CREDENTIALS=$GOOGLE_APPLICATION_CREDENTIALS"
            cat $GOOGLE_APPLICATION_CREDENTIALS
            pulumi login --non-interactive
            pulumi stack select $PULUMI_STACK_NAME
            echo "ok"
            pulumi up --yes --debug

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy
