version: 2.1

pull_requests_only: &pull_requests_only
  filters:
    branches:
      ignore:
        - main
        - develop

commands:
  login: 
    description: "Logs in GCP & Pulumi & Docker"
    steps:
      - run:
          name: Login 
          command: |
            echo "$GCP_SERVICE_ACCOUNT_KEY" > /tmp/gcp-service-account-key.json
            export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-service-account-key.json

            # for this non-interactive command to work PULUMI_ACCESS_TOKEN must exist an env var
            pulumi login --non-interactive

            # docker login is needed by Pulumi up when doing new docker.Image()
            cat $GOOGLE_APPLICATION_CREDENTIALS | docker login -u _json_key --password-stdin https://us-central1-docker.pkg.dev

  determine_workflow_path:
    description: "Determine the workflow path based on git diffs"
    steps:
      - run:
          name: Determine workflow path
          command: |
            if git diff --name-only HEAD^ HEAD | grep -q "backend1/"; then
              echo 'export WORKFLOW_PATH="deploy"' >> $BASH_ENV
            elif git diff --name-only origin/main...$CIRCLE_BRANCH | grep -q "backend1/"; then
              echo 'export WORKFLOW_PATH="use-existing"' >> $BASH_ENV
            else
              echo 'export WORKFLOW_PATH="default-service"' >> $BASH_ENV
            fi

jobs:
  build-and-deploy-preview:
    docker:
      - image: pulumi/pulumi:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Dependencies
          command: |
            npm install
      - determine_workflow_path
      - run:
          name: Deploy to GCP
          command: |

            echo "$GCP_SERVICE_ACCOUNT_KEY" > /tmp/gcp-service-account-key.json
            export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-service-account-key.json

            # for this non-interactive command to work PULUMI_ACCESS_TOKEN must exist an env var
            pulumi login --non-interactive

            # docker login is needed by Pulumi up when doing new docker.Image()
            cat $GOOGLE_APPLICATION_CREDENTIALS | docker login -u _json_key --password-stdin https://us-central1-docker.pkg.dev

            cd infra/shared
            pulumi stack select --create shared
            pulumi up --yes

            cd ../preview
            pulumi stack select --create ${CIRCLE_BRANCH}

            if [ "$WORKFLOW_PATH" = "deploy" ]; then
              echo "creating preview...."
              # pulumi config set pulumi-tests:branch ${CIRCLE_BRANCH}
              pulumi config set branch ${CIRCLE_BRANCH}
              pulumi up --yes --debug
            elif [ "$WORKFLOW_PATH" = "use-existing" ]; then
              echo "use-existing"
              URL=$(pulumi stack output url --stack ${CIRCLE_BRANCH})
              echo "URL= $URL"
            elif [ "$WORKFLOW_PATH" = "default-service" ]; then
              echo "default-service"
              cd ../default-preview
              URL=$(pulumi stack output url --stack default-preview)
              echo "URL= $URL"
            fi

            cd ../

            # pulumi up --yes --json > pulumi-output.json
            # echo "cat pulumi-output.json"
            # cat pulumi-output.json

  update-on-pr-merge:
    docker:
      - image: pulumi/pulumi:latest
    steps:
      - checkout
      - setup_remote_docker
      - login
      - run:
          name: Install Dependencies
          command: |
            npm install
      - run: 
          name: Update default-preview on merge
          command: |
            # on merge, update default-preview with the merged
            cd infra/default-preview
            pulumi stack select --create default-preview
            pulumi up --yes --debug
      - run: 
          name: Destroy resources and delete stack for merged branch 
          command: |
            # on merge, delete resources created 

            git fetch --all
          
            # List branches merged into main
            MERGED_BRANCHES=$(git branch -r --merged origin/main | grep -v 'origin/main$' | sed 's/origin\///')
            echo MERGED_BRANCHES=
            echo $MERGED_BRANCHES

            # Check if MERGED_BRANCHES is empty
            if [ -z "$MERGED_BRANCHES" ]; then
              echo "No merged branches to clean up"
              exit 0  # Exit successfully because it's not an error to have no branches to clean up
            fi

            cd infra/preview
            
            # Loop over the list and perform cleanup
            for stack in $MERGED_BRANCHES; do
              echo "Trying stack=$stack"
              if pulumi stack ls | grep -q $stack; then
                  pulumi stack select $stack
                  pulumi destroy --stack skaparelos/pulumi-tests/$stack --yes
                  pulumi stack rm skaparelos/pulumi-tests/$stack --yes
              else
                  echo "Stack $stack does not exist, skipping."
              fi
            done

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-and-deploy-preview:
          <<: *pull_requests_only
      - update-on-pr-merge:
           filters:
            branches:
              only: main
