version: 2.1

pull_requests_only: &pull_requests_only
  filters:
    branches:
      ignore:
        - main
        - develop

jobs:
  build-and-deploy-preview:
    docker:
      - image: pulumi/pulumi:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Dependencies
          command: |
            npm install
      - run:
          name: Check for file changes
          command: |
            git diff --name-only HEAD^ HEAD > changed_files.txt
            echo "cat changed_files.txt"
            cat changed_files.txt
            if grep -q "backend1/" changed_files.txt; then
              echo 'export BACKEND_CHANGED=true' >> $BASH_ENV
            fi
      - run:
          name: Deploy to GCP
          command: |
            if [ "${BACKEND_CHANGED}" == "true" ]; then
              echo "$GCP_SERVICE_ACCOUNT_KEY" > /tmp/gcp-service-account-key.json
              export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-service-account-key.json

              # for this non-interactive command to work PULUMI_ACCESS_TOKEN must exist an env var
              pulumi login --non-interactive

              # docker login is needed by Pulumi up when doing new docker.Image()
              cat $GOOGLE_APPLICATION_CREDENTIALS | docker login -u _json_key --password-stdin https://us-central1-docker.pkg.dev

              pulumi stack select preview
              pulumi config set branch ${CIRCLE_BRANCH}
              pulumi config set commitsha ${CIRCLE_SHA1}
              pulumi up --yes --debug --json > pulumi-output.json
              echo "cat pulumi-output.json"
              cat pulumi-output.json
            fi

  update-on-pr-merge:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run: pulumi up --stack production

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build-and-deploy-preview:
          <<: *pull_requests_only
      - update-on-pr-merge:
           filters:
            branches:
              only: main
