version: 2.1

pull_requests_only: &pull_requests_only
  filters:
    branches:
      ignore:
        - main
        - develop

jobs:
  deploy:
    docker:
      - image: pulumi/pulumi:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install Dependencies
          command: |
            npm install
      - run:
          name: Check for file changes
          command: |
            git diff --name-only HEAD^ HEAD > changed_files.txt
            echo "cat changed_files.txt"
            cat changed_files.txt
            if grep -q "backend1/" changed_files.txt; then
              echo 'export BACKEND_CHANGED=true' >> $BASH_ENV
            fi
      - run:
          name: Deploy to GCP
          command: |
            if [ "${BACKEND_CHANGED}" == "true" ]; then
              echo "$GCP_SERVICE_ACCOUNT_KEY" > /tmp/gcp-service-account-key.json
              export GOOGLE_APPLICATION_CREDENTIALS=/tmp/gcp-service-account-key.json

              # for this non-interactive command to work PULUMI_ACCESS_TOKEN must exist an env var
              pulumi login --non-interactive
              pulumi stack select $PULUMI_STACK_NAME

              # docker login is needed by Pulumi up when doing new docker.Image()
              cat $GOOGLE_APPLICATION_CREDENTIALS | docker login -u _json_key --password-stdin https://us-central1-docker.pkg.dev

              echo "CIRCLE_BRANCH=$CIRCLE_BRANCH"
              echo "CIRCLE_BRANCH=${CIRCLE_BRANCH}"
              pulumi config set branch ${CIRCLE_BRANCH}
              pulumi up --yes --debug
            fi

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy:
          <<: *pull_requests_only
